### ISSUE TITLE
No Accuracy File gets created while training, exception afterwards cause File not Found

### ISSUE THREAD

**Issue by zaziki23** [bjoern-hempel/keras-machine-learning-framework#1]
Hey,

when i run a training no accuracy file gets created.
On Finish an exceptions is thrown cause that file was not found. 
The same thing happens to me for the flower dataset. 
Reproducable on every run.

What can i do? Can you help me?

[KerasLogNoAccuracyFile.txt](https://github.com/bjoern-hempel/keras-machine-learning-framework/files/4274244/KerasLogNoAccuracyFile.txt)

**Comment by bjoern-hempel** [comment]
Hey, Erik,

it seems that your data is located at C:/Users/[user]/keras/keras-machine-learning-framework/data/raw/productImages and you want to write the data at C:/Users/[user]/keras/keras-machine-learning-framework/data. Can you please try the following, because I'm not sure about the "./" on Windows:

(keras) C:\Users\[user]\keras\keras-machine-learning-framework>ml train --environment-path C:/Users/Erik/keras/keras-machine-learning-framework --data-path=data/raw/productImages --model-file=data/epoch10.h5 -e 10 -v

C:/Users/[user]/keras/keras-machine-learning-framework/data should be created. But I think this is the case if the data is still under raw.

What happens now? For example, does the command writes all models under C:/Users/[user]/keras/keras-machine-learning-framework/data?

I hope it helps.
Greetings Björn

**Comment by zaziki23** [comment]
yep, that worked.

after setting  --environment-path, also the evaluate is working.

just fyi on https://github.com/bjoern-hempel/keras-machine-learning-framework/blob/master/markdown/image-classification/evaluate.md

is the --evaluation-file parameter listed, but that is not a valid parameter anymore
